set(_CATKIN_CURRENT_PACKAGE "ardrone_application_node")
set(ardrone_application_node_MAINTAINER "Charles West <crwest@ncsu.edu>")
set(ardrone_application_node_DEPRECATED "")
set(ardrone_application_node_VERSION "0.0.0")
set(ardrone_application_node_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs" "ardrone_autonomy")
set(ardrone_application_node_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs" "ardrone_autonomy")
set(ardrone_application_node_BUILDTOOL_DEPENDS "catkin")