// Generated by gencpp from file ardrone_command/commandInterface.msg
// DO NOT EDIT!


#ifndef ARDRONE_COMMAND_MESSAGE_COMMANDINTERFACE_H
#define ARDRONE_COMMAND_MESSAGE_COMMANDINTERFACE_H

#include <ros/service_traits.h>


#include <ardrone_command/commandInterfaceRequest.h>
#include <ardrone_command/commandInterfaceResponse.h>


namespace ardrone_command
{

struct commandInterface
{

typedef commandInterfaceRequest Request;
typedef commandInterfaceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct commandInterface
} // namespace ardrone_command


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ardrone_command::commandInterface > {
  static const char* value()
  {
    return "b3948502baec24ce327093a6cf3cf6ea";
  }

  static const char* value(const ::ardrone_command::commandInterface&) { return value(); }
};

template<>
struct DataType< ::ardrone_command::commandInterface > {
  static const char* value()
  {
    return "ardrone_command/commandInterface";
  }

  static const char* value(const ::ardrone_command::commandInterface&) { return value(); }
};


// service_traits::MD5Sum< ::ardrone_command::commandInterfaceRequest> should match 
// service_traits::MD5Sum< ::ardrone_command::commandInterface > 
template<>
struct MD5Sum< ::ardrone_command::commandInterfaceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ardrone_command::commandInterface >::value();
  }
  static const char* value(const ::ardrone_command::commandInterfaceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ardrone_command::commandInterfaceRequest> should match 
// service_traits::DataType< ::ardrone_command::commandInterface > 
template<>
struct DataType< ::ardrone_command::commandInterfaceRequest>
{
  static const char* value()
  {
    return DataType< ::ardrone_command::commandInterface >::value();
  }
  static const char* value(const ::ardrone_command::commandInterfaceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ardrone_command::commandInterfaceResponse> should match 
// service_traits::MD5Sum< ::ardrone_command::commandInterface > 
template<>
struct MD5Sum< ::ardrone_command::commandInterfaceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ardrone_command::commandInterface >::value();
  }
  static const char* value(const ::ardrone_command::commandInterfaceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ardrone_command::commandInterfaceResponse> should match 
// service_traits::DataType< ::ardrone_command::commandInterface > 
template<>
struct DataType< ::ardrone_command::commandInterfaceResponse>
{
  static const char* value()
  {
    return DataType< ::ardrone_command::commandInterface >::value();
  }
  static const char* value(const ::ardrone_command::commandInterfaceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARDRONE_COMMAND_MESSAGE_COMMANDINTERFACE_H
