// Generated by gencpp from file ardrone_command/commandInterfaceResponse.msg
// DO NOT EDIT!


#ifndef ARDRONE_COMMAND_MESSAGE_COMMANDINTERFACERESPONSE_H
#define ARDRONE_COMMAND_MESSAGE_COMMANDINTERFACERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ardrone_command
{
template <class ContainerAllocator>
struct commandInterfaceResponse_
{
  typedef commandInterfaceResponse_<ContainerAllocator> Type;

  commandInterfaceResponse_()
    : received(false)  {
    }
  commandInterfaceResponse_(const ContainerAllocator& _alloc)
    : received(false)  {
    }



   typedef uint8_t _received_type;
  _received_type received;




  typedef boost::shared_ptr< ::ardrone_command::commandInterfaceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ardrone_command::commandInterfaceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct commandInterfaceResponse_

typedef ::ardrone_command::commandInterfaceResponse_<std::allocator<void> > commandInterfaceResponse;

typedef boost::shared_ptr< ::ardrone_command::commandInterfaceResponse > commandInterfaceResponsePtr;
typedef boost::shared_ptr< ::ardrone_command::commandInterfaceResponse const> commandInterfaceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ardrone_command::commandInterfaceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ardrone_command::commandInterfaceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ardrone_command

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'ardrone_command': ['/home/hewhosurvives/c++/randomProjects/ros/catkin_ws/src/ardrone_command/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ardrone_command::commandInterfaceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ardrone_command::commandInterfaceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ardrone_command::commandInterfaceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ardrone_command::commandInterfaceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardrone_command::commandInterfaceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardrone_command::commandInterfaceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ardrone_command::commandInterfaceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd4152e077925db952c78baadb1e48b7";
  }

  static const char* value(const ::ardrone_command::commandInterfaceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd4152e077925db9ULL;
  static const uint64_t static_value2 = 0x52c78baadb1e48b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::ardrone_command::commandInterfaceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ardrone_command/commandInterfaceResponse";
  }

  static const char* value(const ::ardrone_command::commandInterfaceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ardrone_command::commandInterfaceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool received\n\
\n\
";
  }

  static const char* value(const ::ardrone_command::commandInterfaceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ardrone_command::commandInterfaceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.received);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct commandInterfaceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ardrone_command::commandInterfaceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ardrone_command::commandInterfaceResponse_<ContainerAllocator>& v)
  {
    s << indent << "received: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.received);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDRONE_COMMAND_MESSAGE_COMMANDINTERFACERESPONSE_H
