// Generated by gencpp from file ardrone_command/serialized_ardrone_command.msg
// DO NOT EDIT!


#ifndef ARDRONE_COMMAND_MESSAGE_SERIALIZED_ARDRONE_COMMAND_H
#define ARDRONE_COMMAND_MESSAGE_SERIALIZED_ARDRONE_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ardrone_command/serialized_ardrone_command_part.h>
#include <ardrone_command/serialized_ardrone_command_part.h>

namespace ardrone_command
{
template <class ContainerAllocator>
struct serialized_ardrone_command_
{
  typedef serialized_ardrone_command_<ContainerAllocator> Type;

  serialized_ardrone_command_()
    : command()
    , subcommands()  {
    }
  serialized_ardrone_command_(const ContainerAllocator& _alloc)
    : command(_alloc)
    , subcommands(_alloc)  {
    }



   typedef  ::ardrone_command::serialized_ardrone_command_part_<ContainerAllocator>  _command_type;
  _command_type command;

   typedef std::vector< ::ardrone_command::serialized_ardrone_command_part_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ardrone_command::serialized_ardrone_command_part_<ContainerAllocator> >::other >  _subcommands_type;
  _subcommands_type subcommands;




  typedef boost::shared_ptr< ::ardrone_command::serialized_ardrone_command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ardrone_command::serialized_ardrone_command_<ContainerAllocator> const> ConstPtr;

}; // struct serialized_ardrone_command_

typedef ::ardrone_command::serialized_ardrone_command_<std::allocator<void> > serialized_ardrone_command;

typedef boost::shared_ptr< ::ardrone_command::serialized_ardrone_command > serialized_ardrone_commandPtr;
typedef boost::shared_ptr< ::ardrone_command::serialized_ardrone_command const> serialized_ardrone_commandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ardrone_command::serialized_ardrone_command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ardrone_command::serialized_ardrone_command_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ardrone_command

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'ardrone_command': ['/home/hewhosurvives/c++/randomProjects/ros/catkin_ws/src/ardrone_command/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ardrone_command::serialized_ardrone_command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ardrone_command::serialized_ardrone_command_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ardrone_command::serialized_ardrone_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ardrone_command::serialized_ardrone_command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardrone_command::serialized_ardrone_command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardrone_command::serialized_ardrone_command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ardrone_command::serialized_ardrone_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ffbcc12c7c708ba17b5a85205ec7941d";
  }

  static const char* value(const ::ardrone_command::serialized_ardrone_command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xffbcc12c7c708ba1ULL;
  static const uint64_t static_value2 = 0x7b5a85205ec7941dULL;
};

template<class ContainerAllocator>
struct DataType< ::ardrone_command::serialized_ardrone_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ardrone_command/serialized_ardrone_command";
  }

  static const char* value(const ::ardrone_command::serialized_ardrone_command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ardrone_command::serialized_ardrone_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#ROS message format doesn't support recursive definitions (a message type cannot contain more messages of the same type), so commands will have to be decomposed when they are serialized and will not be exactly the same on the other side\n\
serialized_ardrone_command_part command\n\
serialized_ardrone_command_part[] subcommands \n\
\n\
\n\
================================================================================\n\
MSG: ardrone_command/serialized_ardrone_command_part\n\
uint32 type\n\
string[] strings\n\
float64[] doubles\n\
int64[] integers\n\
uint32[] flightAnimations\n\
uint32[] ledAnimations\n\
";
  }

  static const char* value(const ::ardrone_command::serialized_ardrone_command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ardrone_command::serialized_ardrone_command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.subcommands);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct serialized_ardrone_command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ardrone_command::serialized_ardrone_command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ardrone_command::serialized_ardrone_command_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    s << std::endl;
    Printer< ::ardrone_command::serialized_ardrone_command_part_<ContainerAllocator> >::stream(s, indent + "  ", v.command);
    s << indent << "subcommands[]" << std::endl;
    for (size_t i = 0; i < v.subcommands.size(); ++i)
    {
      s << indent << "  subcommands[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ardrone_command::serialized_ardrone_command_part_<ContainerAllocator> >::stream(s, indent + "    ", v.subcommands[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDRONE_COMMAND_MESSAGE_SERIALIZED_ARDRONE_COMMAND_H
