#ifndef ARDRONEENUMSHPP
#define ARDRONEENUMSHPP

enum droneCurrentState
{
UNKNOWN_STATE = 0,
INITIALIZED = 1,
LANDED = 2,
FLYING = 3,
HOVERING = 4,
TEST = 5,
TAKING_OFF = 6,
LANDING = 7,
LOOPING = 8
};

enum LEDAnimationType
{
BLINK_GREEN_RED, 
BLINK_GREEN,
BLINK_RED,
BLINK_ORANGE,
SNAKE_GREEN_RED,
FIRE,
STANDARD,
RED,
GREEN,
RED_SNAKE,
BLANK,
LEFT_GREEN_RIGHT_RED,
LEFT_RED_RIGHT_GREEN,
BLINK_STANDARD
};

enum flightAnimationType
{
ARDRONE_ANIM_PHI_M30_DEG, 
ARDRONE_ANIM_PHI_30_DEG, 
ARDRONE_ANIM_THETA_M30_DEG, 
ARDRONE_ANIM_THETA_30_DEG,
ARDRONE_ANIM_THETA_20DEG_YAW_200DEG, 
ARDRONE_ANIM_THETA_20DEG_YAW_M200DEG, 
ARDRONE_ANIM_TURNAROUND,
ARDRONE_ANIM_TURNAROUND_GODOWN, 
ARDRONE_ANIM_YAW_SHAKE, 
ARDRONE_ANIM_YAW_DANCE, 
ARDRONE_ANIM_PHI_DANCE,
ARDRONE_ANIM_THETA_DANCE, 
ARDRONE_ANIM_VZ_DANCE, 
ARDRONE_ANIM_WAVE, 
ARDRONE_ANIM_PHI_THETA_MIXED,
ARDRONE_ANIM_DOUBLE_PHI_THETA_MIXED, 
ARDRONE_ANIM_FLIP_AHEAD, 
ARDRONE_ANIM_FLIP_BEHIND, 
ARDRONE_ANIM_FLIP_LEFT,
ARDRONE_ANIM_FLIP_RIGHT
};







#endif
